"""Storage interface for the BL (schema `bl`). Implementations: PgStore (prod), MemoryStore (tests)."""

from __future__ import annotations

from datetime import datetime
from typing import Any, Protocol
from uuid import UUID

AgentRow = dict[str, Any]
RunRow = dict[str, Any]
EventRow = dict[str, Any]


class Store(Protocol):
    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def ping(self) -> bool: ...

    # agents
    async def seed_agents(self, agents: list[AgentRow]) -> None: ...
    async def list_agents(self, *, only_enabled: bool) -> list[AgentRow]: ...
    async def get_agent(self, agent_id: str) -> AgentRow | None: ...
    async def update_agent(self, agent_id: str, patch: dict[str, Any]) -> AgentRow | None: ...

    # runs
    async def create_run(self, run: RunRow) -> RunRow: ...
    async def get_run(self, run_id: UUID) -> RunRow | None: ...
    async def update_run(self, run_id: UUID, **fields: Any) -> RunRow | None: ...
    async def list_runs(
        self,
        *,
        user_sub: str | None = None,
        agent_id: str | None = None,
        status: str | None = None,
        limit: int = 50,
        offset: int = 0,
    ) -> tuple[list[RunRow], int]: ...
    async def count_runs_since(self, user_sub: str, since: datetime) -> int: ...
    async def thread_belongs_to(self, user_sub: str, agent_id: str, thread_id: str) -> bool: ...
    async def fail_stale_runs(self) -> int: ...

    # events
    async def append_event(self, run_id: UUID, type_: str, data: dict[str, Any]) -> int: ...
    async def list_events(self, run_id: UUID, after_seq: int = 0) -> list[EventRow]: ...

    # admin
    async def stats(self, since: datetime) -> dict[str, Any]: ...
    async def get_setting(self, key: str) -> Any | None: ...
    async def put_setting(self, key: str, value: Any) -> None: ...
