server {
	listen 80;
	listen [::]:80;
	server_name osipcraft.ru www.osipcraft.ru;

	root /var/www/osipcraft;
	index index.html;

	gzip on;
	gzip_types text/plain text/css application/javascript application/json image/svg+xml;

	location = /icon {
		default_type image/png;
	}

	location = /opengraph-image {
		default_type image/png;
	}

	location / {
		try_files $uri $uri.html $uri/ /index.html;
	}

	error_page 404 /404.html;
}
